using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;

namespace VinculoBackend.Web.Infrastructure;

/// <summary>
/// Adds human-readable summaries and descriptions to the ASP.NET Core Identity endpoints
/// registered by <c>MapIdentityApi</c>. Those endpoints are generated by the framework and
/// cannot be annotated with <see cref="EndpointSummaryAttribute"/> or
/// <see cref="EndpointDescriptionAttribute"/> directly, so metadata is applied here by
/// matching on the operation's relative path (and HTTP method for ambiguous paths).
/// </summary>
internal sealed class IdentityApiOperationTransformer : IOpenApiOperationTransformer
{
    private static readonly Dictionary<string, (string Summary, string Description)> _metadata = new()
    {
        ["api/Users/register"]                  = ("Cadastrar", "Cria uma nova conta de usuário."),
        ["api/Users/login"]                     = ("Entrar", "Autentica um usuário. Use ?useCookies=true para autenticação baseada em cookies."),
        ["api/Users/refresh"]                   = ("Renovar token", "Retorna um novo token de acesso usando um token de renovação válido."),
        ["api/Users/confirmEmail"]              = ("Confirmar e-mail", "Confirma o e-mail do usuário usando o token enviado por e-mail."),
        ["api/Users/resendConfirmationEmail"]   = ("Reenviar confirmação de e-mail", "Envia um novo link de confirmação para o endereço informado."),
        ["api/Users/forgotPassword"]            = ("Esqueci a senha", "Envia um link de redefinição de senha para o e-mail informado."),
        ["api/Users/resetPassword"]             = ("Redefinir senha", "Redefine a senha do usuário usando o token enviado por e-mail."),
        ["api/Users/manage/2fa"]                = ("Gerenciar autenticação em dois fatores", "Ativa, desativa ou consulta as configurações de autenticação em dois fatores."),
        ["api/Users/manage/info GET"]           = ("Consultar dados da conta", "Retorna o e-mail do usuário atual e o status da autenticação em dois fatores."),
        ["api/Users/manage/info POST"]          = ("Atualizar dados da conta", "Atualiza o e-mail ou a senha do usuário atual."),
    };

    public Task TransformAsync(OpenApiOperation operation, OpenApiOperationTransformerContext context, CancellationToken cancellationToken)
    {
        var path = context.Description.RelativePath ?? "";
        var key = $"{path} {context.Description.HttpMethod?.ToUpperInvariant()}";

        if (_metadata.TryGetValue(key, out var meta) || _metadata.TryGetValue(path, out meta))
        {
            operation.Summary = meta.Summary;
            operation.Description = meta.Description;
        }

        return Task.CompletedTask;
    }
}